'use client';
import{useRef,useState}from'react';
import{Globe2,Layers,Map,Plus,Minus,RotateCcw,Maximize,Info,ArrowUpRight,MapPin,ChevronRight,Camera,Eye,EyeOff,Rotate3d,Pause,Navigation2,List,X,Move,Footprints}from'lucide-react';
import CampusView,{type CampusApi}from'@/components/campus-view';
import CampusTourDialog from'@/components/campus-tour-dialog';
import BuildingVisitDialog from '@/components/building-visit-dialog';
import {type CampusTour} from '@/lib/campus/visits';
import WalkHud from'@/components/walk-hud';
import type{WalkState}from'@/lib/campus/walk-controller';
import{Tabs,TabsList,TabsTrigger}from'@/components/ui/tabs';
import{Dialog,DialogContent,DialogTitle,DialogDescription}from'@/components/ui/dialog';
import{Sheet,SheetContent,SheetTitle,SheetDescription}from'@/components/ui/sheet';
import{places,featuredIds,SOURCE,type ViewMode}from'@/lib/campus/data';
export default function Home(){
 const[mode,setMode]=useState<ViewMode>('world'),[selected,setSelected]=useState<string|null>(null),[labels,setLabels]=useState(true),[orbit,setOrbit]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[directory,setDirectory]=useState(false),[about,setAbout]=useState(false),[tour,setTour]=useState<CampusTour|null>(null);
 const[entry,setEntry]=useState<string|null>(null);
 const[avatar,setAvatar]=useState<'boy'|'girl'>('boy'),[passport,setPassport]=useState(false);
 const[walkState,setWalkState]=useState<WalkState>({active:false,nearby:null,visited:[],x:37,z:73,yaw:0,game:{phase:'off',score:0,attempts:0,power:0,aim:0,charging:false,message:''}});
 const api=useRef<CampusApi|null>(null);const place=places.find(p=>p.id===selected);
 const choose=(id:string)=>{setSelected(id);setDirectory(false);};
 const visit=(id:string)=>{if(!places.some(p=>p.id===id))return;setSelected(null);setDirectory(false);setEntry(id);};
 const changeMode=(value:unknown)=>{setSelected(null);setDirectory(false);setPassport(false);setMode(value as ViewMode);setOrbit(false);};
 const walkTo=(id:string)=>{changeMode('walk');api.current?.walk.goTo(id);};
 const fullscreen=()=>{if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});else void document.documentElement.requestFullscreen().catch(()=>{});};
 return <main className={'campus-app mode-'+mode}>
  <CampusView mode={mode} selected={selected} labels={labels} orbit={orbit} avatar={avatar} paused={!!selected||!!tour||!!entry||about||directory||passport} suspended={!!entry||!!tour} onWalkState={setWalkState} onWalkInteract={visit} onSelect={choose} onReady={()=>setReady(true)} onError={setError} apiRef={api}/>
  <header className="topbar">
   <button className="school-brand" onClick={()=>{setSelected(null);api.current?.reset();}} aria-label="Chong Hwa campus home"><img className="school-logo" src="/branding/chkl-official-header.png" alt="Chong Hwa Independent High School official logo" width="753" height="166"/></button>
   <Tabs value={mode} onValueChange={changeMode} className="view-tabs"><TabsList aria-label="Campus view"><TabsTrigger value="world"><Globe2/>World</TabsTrigger><TabsTrigger value="campus"><Layers/>3D campus</TabsTrigger><TabsTrigger value="plan"><Map/>Flat plan</TabsTrigger><TabsTrigger value="walk"><Footprints/>Walk</TabsTrigger></TabsList></Tabs>
   <button className="about-button" onClick={()=>setAbout(true)}><Info size={17}/><span>About this campus</span></button>
  </header>
  <section className="map-intro" aria-label="Campus location"><div className="location-line"><MapPin size={14}/> KUALA LUMPUR, MALAYSIA</div><h1>Your school.<br/>A little world.</h1><p>Explore Chong Hwa, one familiar<br className="desktop-break"/> corner at a time.</p><button className={'directory-trigger '+(directory?'active':'')} onClick={()=>{setDirectory(v=>!v);setSelected(null);}} aria-expanded={directory}><List size={17}/> Explore the campus <span>{places.length}</span></button><button className="start-walking" onClick={()=>changeMode('walk')}><Footprints size={18}/> Walk as a student</button></section>
  {directory&&<section className="directory-panel" aria-label="Campus directory"><div className="panel-heading"><h2>Campus directory</h2><button onClick={()=>setDirectory(false)} aria-label="Close directory"><X size={18}/></button></div><div className="directory-list">{places.map(p=><button key={p.id} onClick={()=>choose(p.id)}><span className="block-letter">{p.id.length===1?p.id:<MapPin size={14}/>}</span><span><strong>{p.name}</strong><span lang="zh">{p.zh}</span></span><ChevronRight size={16}/></button>)}</div></section>}
  {!ready&&!error&&<div className="loading-map" role="status"><span className="loading-model"/><strong>Bringing the campus to life…</strong><span>Chong Hwa, Kuala Lumpur</span></div>}
  {error&&<section className="map-error" role="alert"><p>{error}</p><button onClick={()=>setDirectory(true)}>Explore the campus directory</button><a href="/media/campus-map.jpg" target="_blank" rel="noreferrer">View the official campus map <ArrowUpRight size={14}/></a></section>}
  <div className="compass" aria-label="Illustrated map orientation"><Navigation2 size={22}/><span>MAP</span></div>
  <nav className="map-tools" aria-label="Map controls"><button onClick={()=>api.current?.zoom(1.2)} aria-label="Zoom in" title="Zoom in"><Plus/></button><button onClick={()=>api.current?.zoom(1/1.2)} aria-label="Zoom out" title="Zoom out"><Minus/></button><span/><button onClick={()=>{api.current?.reset();setOrbit(false);}} aria-label="Reset campus view" title="Reset view"><RotateCcw size={19}/></button><button onClick={fullscreen} aria-label="Toggle fullscreen" title="Fullscreen"><Maximize size={18}/></button></nav>
  <div className="display-tools"><button onClick={()=>setLabels(v=>!v)} aria-pressed={labels}>{labels?<Eye size={16}/>:<EyeOff size={16}/>}<span>Labels</span></button><span/><button onClick={()=>setOrbit(v=>!v)} disabled={mode==='plan'||mode==='walk'} aria-pressed={orbit}>{orbit?<Pause size={16}/>:<Rotate3d size={16}/>}<span>{orbit?'Pause orbit':'Auto orbit'}</span></button></div>
  <section className="landmark-strip" aria-label="Campus highlights"><div className="strip-title"><span>Familiar places</span><span>Select a place to explore <ChevronRight size={13}/></span></div><div className="landmark-list">{featuredIds.map(id=>{const p=places.find(p=>p.id===id)!;return <button key={id} className={'landmark-item '+(selected===id?'selected':'')} onClick={()=>choose(id)}>{p.image?<img src={'/thumbs/'+p.image} alt="" width="90" height="64"/>:<span className="landmark-letter">{p.id}</span>}<span><span lang="zh">{p.zh.split(' · ')[0]}</span><strong>{p.name}</strong></span><ArrowUpRight size={14}/></button>;})}</div></section>
  {mode==='walk'&&<WalkHud state={walkState} avatar={avatar} onAvatar={setAvatar} api={api.current} passport={passport} setPassport={setPassport} blocked={!!selected||!!tour||!!entry||about||directory||passport} onGoTo={walkTo}/>}
  <footer className="map-footer"><span><Move size={13}/><span>{mode==='walk'?'WASD to walk · E to explore · Drag to look':(mode==='plan'?'Drag to pan':'Drag to orbit')+' · Scroll to zoom · Select a building'}</span></span><button onClick={()=>setAbout(true)}>Illustrated campus · Official school references <ArrowUpRight size={12}/></button></footer>
  <Sheet open={!!place} onOpenChange={open=>{if(!open)setSelected(null);}} modal={false}><SheetContent side="right" className="place-sheet" aria-describedby="place-description"><div className="place-photo">{place?.image?<img src={'/thumbs/'+place.image} alt={place.name}/>:<div className="place-monogram"><span>{place?.id}</span><Layers size={48}/></div>}<span className="photo-caption">{place?.image?'Official school imagery':'Campus landmark'}</span></div><div className="place-body"><div className="place-category">{place?.kind}{place?.floors&&<span>{place.floors} floors</span>}</div><p className="place-chinese" lang="zh">{place?.zh}</p><SheetTitle className="place-title">{place?.name}</SheetTitle><SheetDescription id="place-description" className="place-description">{place?.description}</SheetDescription>{place?.views&&<div className="place-tours"><h3><Camera size={16}/> Step inside · 360°</h3>{place.views.map(v=><button key={v.image} onClick={()=>place&&setTour({...v,placeId:place.id})}><span>{v.name}</span><ArrowUpRight size={17}/></button>)}</div>}{place&&!place.views?.length&&<p className="no-panorama">{place.id==='L'?'An official arena photograph is available. A verified 360° view has not been located in the school sources.':'No verified 360° view is currently mapped to this building. Its location and facilities are shown here.'}</p>}{place?.id==='L'&&<a className="source-link" href="/media/arena-photo.jpg" target="_blank" rel="noreferrer">Open full arena photograph <ArrowUpRight size={14}/></a>}<button className="enter-building" onClick={()=>place&&visit(place.id)}><Footprints size={17}/> Explore in 3D or choose a panorama</button><button className="walk-here" onClick={()=>place&&walkTo(place.id)}><Footprints size={17}/> Walk here</button><a className="source-link" href={SOURCE} target="_blank" rel="noreferrer">School facilities & source <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
  <Dialog open={about} onOpenChange={setAbout}><DialogContent className="about-dialog"><DialogTitle>Your campus, ready to explore.</DialogTitle><DialogDescription>A little digital world of Chong Hwa Independent High School, Kuala Lumpur.</DialogDescription><div className="about-modes"><p><Footprints/><span><strong>Walk as a student</strong>Choose a student, explore entrances, fill your campus passport and play basketball.</span></p><p><Globe2/><span><strong>World</strong>School landmarks spread across a complete little world.</span></p><p><Layers/><span><strong>3D campus</strong>Flatten the ground and orbit the buildings.</span></p><p><Map/><span><strong>Flat plan</strong>Look straight down. Drag to pan and find your way.</span></p></div><p>World view spreads the school landmarks around the globe, connected by illustrative roads, trees and neighbourhood scenery. The 3D campus and flat plan bring the buildings back to the layout of the school’s official campus map. Heights are based on listed floors where available. Photographic surface materials add detail to reconstructed buildings. Shapes, distances, landscaping and surroundings are illustrative, not a surveyed model. Map orientation is schematic.</p><p>Selected landmarks include real 360° imagery published by the school. Student clothing follows the official junior uniform guide. Teachers are illustrative characters. Signs and building forms are simplified from official references; 360° tours use actual school photos. This is an independent campus visualization. Architectural material textures are CC0 assets from Poly Haven; these are representative materials, not scans of the school.</p><div className="about-links"><a href="/media/campus-map.jpg" target="_blank" rel="noreferrer">Official campus map <ArrowUpRight size={15}/></a><a href="https://polyhaven.com/" target="_blank" rel="noreferrer">Material textures · Poly Haven <ArrowUpRight size={15}/></a><a href={SOURCE} target="_blank" rel="noreferrer">Photos & virtual tours <ArrowUpRight size={15}/></a></div><p className="keyboard-note">Keyboard: use Tab to reach controls, arrow keys on the model to pan, + / − to zoom, and Home to reset. Reduced motion follows your device setting.</p></DialogContent></Dialog>
  {entry&&<BuildingVisitDialog key={entry} place={places.find(p=>p.id===entry)!} onClose={()=>setEntry(null)}/>}
  <CampusTourDialog tour={tour} onChange={setTour}/>
 </main>;
}
