export type ViewMode = 'world' | 'campus' | 'plan' | 'walk';
export type Place = { id:string; name:string; zh:string; kind:string; x:number; z:number; w:number; d:number; h:number; floors?:number; shape?:string; image?:string; views?:{name:string;image:string}[]; description:string; source?:string };
export const SOURCE='https://www.chonghwakl.edu.my/campusfacilities/';
export const places:Place[]=[
{id:'K',name:'Chong Hwa Building',zh:'中华楼',kind:'Learning & community',x:9,z:49,w:35,d:23,h:44,floors:14,shape:'tower',image:'DataranCHKL-1.jpg',views:[{name:'Chong Hwa Square',image:'DataranCHKL-1.jpg'},{name:'Library · Level 12',image:'pusatsumber-1.jpg'},{name:'Library · Level 13',image:'pusatsumber-3.jpg'},{name:'Heritage museum',image:'wenshiguan-1.jpg'},{name:'Ekovest auditorium',image:'zaichunjiangtang-1.jpg'},{name:'Dato Tan Hwa Ho auditorium',image:'naduchenhuahejiangtang-1.jpg'},{name:'Recording studio',image:'luyinshi-1.jpg'},{name:'Photography studio',image:'sheyingpeng-1.jpg'}],description:'The landmark at the front of campus. Fourteen floors bring together Chong Hwa Square, auditoriums, the heritage museum and learning spaces. The library and resource centre occupy levels 12 and 13.'},
{id:'A',name:'Kong Chen Hall',zh:'光前堂',kind:'Gathering places',x:55,z:25,w:43,d:23,h:12,floors:2,shape:'hall',image:'guangqiantang-1.jpg',views:[{name:'Inside the hall',image:'guangqiantang-1.jpg'}],description:'The school hall beside Chong Hwa Building. An assembly and event space at the heart of school life, with a distinctive long roof.'},
{id:'L',name:'Sports Arena',zh:'联课活动中心 · 体育馆',kind:'Sport & activities',x:-24,z:-58,w:70,d:42,h:20,floors:5,shape:'arena',image:'arena.jpg',description:'A multi-storey sports and co-curricular centre with a swimming pool on the mezzanine level. The Sky Track sits on its roof, above the rest of the campus.'},
{id:'D',name:'Quadrangular Block',zh:'国字楼',kind:'Learning & community',x:50,z:-28,w:31,d:28,h:14,floors:4,shape:'courtyard',image:'guozilouyuanxingwutai-1.jpg',views:[{name:'Circular stage',image:'guozilouyuanxingwutai-1.jpg'}],description:'A four-storey block wrapped around an open courtyard. Its circular stage is one of the campus spaces featured in the school’s virtual tour.'},
{id:'I',name:'Technology Block',zh:'成枫工艺楼',kind:'Learning & community',x:-72,z:35,w:15,d:37,h:17,floors:5,description:'The five-storey technology block on the left side of the official campus map, across from the courts and hostel buildings.'},
{id:'J',name:'Classroom Block',zh:'教室楼',kind:'Learning & community',x:-31,z:59,w:35,d:15,h:17,floors:5,description:'A long five-storey classroom building along the front edge of campus, next to Chong Hwa Building.'},
{id:'G',name:'Boys’ Hostel',zh:'男生宿舍',kind:'Campus life',x:-39,z:-21,w:45,d:12,h:17,description:'The boys’ hostel sits below the sports arena in the official campus layout. Residential accommodation is grouped around the western courtyard.'},
{id:'H',name:'Girls’ Hostel',zh:'女生宿舍',kind:'Campus life',x:-33,z:17,w:15,d:35,h:19,image:'meishige-1.jpg',views:[{name:'Hostel canteen',image:'meishige-1.jpg'}],description:'The girls’ hostel borders the inner courtyard. The official directory lists the hostel canteen at ground level.'},
{id:'F',name:'Administration Building',zh:'行政楼',kind:'Learning & community',x:-3,z:-18,w:16,d:18,h:18,floors:5,views:[{name:'Administration small hall',image:'xingzhenglouxiaolitang-1.jpg'}],description:'The five-storey administration building sits between the boys’ hostel and the Student Block at the rear of the central courtyard.'},
{id:'E',name:'Student Block',zh:'学生楼',kind:'Learning & community',x:22,z:-16,w:26,d:13,h:14,floors:4,description:'A four-storey block on the courtyard’s northern side, linking the administrative side of campus with the Quadrangular Block.'},
{id:'B',name:'Canteen Block',zh:'食堂楼',kind:'Campus life',x:80,z:0,w:16,d:19,h:14,floors:4,image:'meishifang-1.jpg',views:[{name:'Food court',image:'meishifang-1.jpg'}],description:'The four-storey canteen block beside Kong Chen Hall, a familiar stop for meals and time between classes.'},
{id:'C',name:'Commerce Studies Block',zh:'商科楼',kind:'Learning & community',x:80,z:-25,w:22,d:12,h:14,floors:4,description:'A four-storey teaching block on the eastern edge of the school’s illustrated campus map.'},
{id:'pond',name:'Bian Xing Hu',zh:'变形湖',kind:'Campus life',x:6,z:17,w:15,d:11,h:1,shape:'pond',image:'bianxinghu-1.jpg',views:[{name:'Around the pond',image:'bianxinghu-1.jpg'}],description:'A small courtyard pond garden with yellow tiered edges, paving and trees, beside a campus footbridge. Take a look around this space in the school’s official 360° panorama.'},
{id:'gate',name:'Main Entrance',zh:'学校大门口',kind:'Arriving at school',x:37,z:64,w:14,d:4,h:6,shape:'gate',image:'xuexiaodamenkou-1.jpg',views:[{name:'At the school gates',image:'xuexiaodamenkou-1.jpg'}],description:'Start here. The main entrance welcomes students and visitors along the front of the campus.'}
];
export const featuredIds=['K','L','A','D','pond','gate'];
